### ISSUE TITLE
Timeout does not work

### ISSUE THREAD

**Issue by tomswinkels** [stefanak-michal/Bolt#34]
Hi,

One of my neo4j servers had a problem. But the script has a default timeout of 15 but didn't work.

**Comment by stefanak-michal** [comment]
It looks like timeout for socket_connect is from ini `default_socket_timeout`. Timeout set with socket_set_option works for established connection. Sadly I can't use method ini_set because it can be disabled for security reasons.

You can change it by yourself in php.ini file or with ini_set before creating Bolt instance.

I'll add this info to wiki.
