### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by tomswinkels** [stefanak-michal/Bolt#35]
Option to added TLS support in socket_connect.

**Comment by tim-hanssen** [comment]
Changing the config`dbms.connector.bolt.tls_level=OPTIONAL` to `dbms.connector.bolt.tls_level=REQUIRED` to ensure all connections to the bolt protocol are using TLS. Will throw now an error:

`2020-11-13 12:34:59.469+0000 ERROR [o.n.b.t.p.ProtocolHandshaker] Fatal error occurred during protocol handshaking: [id: 0x4c8fb0c4, L:/167.172.37.164:7687 - R:/87.233.165.57:55806] An unencrypted connection attempt was made where encryption is required.`

**Comment by stefanak-michal** [comment]
Looks like the standard php socket which I use doesn't support certificates. I made a new connection class with stream_socket. You can check out the code here: https://github.com/stefanak-michal/Bolt/tree/issue/35_tls

But I had to change Bolt constructor. Now it accepts IConnection instance instead of connection parameters (ip, port, timeout). SSL parameters are specified with method setSslContextOptions on connection. Here is sample code.

```php
$conn = new \Bolt\connection\StreamSocket();
// https://www.php.net/manual/en/context.ssl.php
$conn->setSslContextOptions([
    'local_cert'=> 'd:\www\bolt\cert\public_cert.pem',
    'local_pk' => 'd:\www\bolt\cert\private_key.pem',
    'passphrase' => 'bolt',
    'allow_self_signed' => true,
    'verify_peer' => false,
    'verify_peer_name' => false
]);
$bolt = new \Bolt\Bolt($conn);
```

I disabled verify because I was testing on localhost.

_I feel like in last time I just fight with ssl certificates everywhere._

**Comment by stefanak-michal** [comment]
@tomswinkels @tim-hanssen Let me know if you will try this branch and how it works for you. Then I can merge it into master.

@stefanak-michal Don't forget update wiki if so.

**Comment by tomswinkels** [comment]
Very nice, it works.

We do not use the local_pk, only the local_cert is required.

`$conn = new \Bolt\connection\StreamSocket($ip,$port);
$conn->setSslContextOptions([
    'local_cert'=> storage_path('app/cert.pem'),
    'passphrase' => 'bolt',
    'allow_self_signed' => true,
    'verify_peer' => false,
    'verify_peer_name' => false
]);

$bolt = new \Bolt\Bolt($conn);`

**Comment by stefanak-michal** [comment]
@tomswinkels Don't you have certificate signed by authority? It will be nice to test it with non self signed certificate.

**Comment by tim-hanssen** [comment]
Hey @stefanak-michal we tested it with signed certificates by Comodo ca. De pem file includes both the certificate as the private key combined.

**Comment by stefanak-michal** [comment]
Great, thanks for feedback.
