### ISSUE TITLE
Examples are needed

### ISSUE THREAD

**Issue by GinoPane** [stefanak-michal/Bolt#9]
Hi!
Do you plan to add any examples of real usage? How to connect, make Cypher queries etc.
Thanks.

**Comment by stefanak-michal** [comment]
I think `index.php` contains everything necessary. There is a connection, version selection, executing queries and pulling response. But I can add it to readme.

How to make cypher queries shouldn't be part of this repository, because this is about Bolt protocol. Manual and explanation about cypher queries you can find at [neo4j website](https://neo4j.com/developer/cypher/)

**Comment by GinoPane** [comment]
No, I meant how to make queries with this package :smiley:

Anyway, I see, that `index.php` definitely contains examples with queries also.

Thanks.

By the way, in readme you mentioned the library which you did not like because it has a lot of dependencies. Did you mean a the library from Graphaware?

**Comment by stefanak-michal** [comment]
@GinoPane `Did you mean a the library from Graphaware?` Yes, I did.
